### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shaman-arto** [SpheroidUniverse/SpheroidScript#1]
Good day, developers!
Error
![Error 1](https://user-images.githubusercontent.com/69425295/89733845-79a9db80-da82-11ea-8eed-5f9fdb6f2c7f.jpg)
 | File not found: /assets/jump.ogg

**Comment by SpheroidUniverse** [comment]
File "/assets/jump.ogg" is uploaded. Thanks for the feedback!
