### ISSUE TITLE
small text error in the server ok's when publishing the app.

### ISSUE THREAD

**Issue by sparra1970** [SpheroidUniverse/SpheroidScript#3]
It says: "Server side side been successfully compiled."
It should say: "Server side has been successfully compiled."

![image](https://user-images.githubusercontent.com/30248584/89735906-172dec80-da3c-11ea-8797-396f6e82208e.png)

**Comment by kostyazen** [comment]
looks reasonable

**Comment by SpheroidUniverse** [comment]
The typo is fixed now. Thanks! @sparra1970
