### ISSUE TITLE
Icon on Map tab

### ISSUE THREAD

**Issue by hodlinn** [SpheroidUniverse/SpheroidScript#5]
I was able to work everything fine but when opened, the coins on the navigation map still that of Spheroid even after all was changed. @SpheroidUniverse

**Comment by SpheroidUniverse** [comment]
We've solved this in the latest version of XRHub.

We've added the "icon" parameter to the "MapMarker" constructor which allows you to control the coin appearance on the map. Here is an example use case:
```
val marker = MapMarker(location = coin.location, icon = mapIcon)
```

We've also updated the [Quickstart tutorial](https://github.com/SpheroidUniverse/SpheroidScript/tree/master/examples/CoinQuest) and its [source code](https://github.com/SpheroidUniverse/SpheroidScript/tree/master/examples/CoinQuest/src).

 Please, follow these steps to upgrade your app:
- update [XRHub](https://play.google.com/store/apps/details?id=io.spheroid.spheroidandroid) to the latest version 5.0.2 on your mobile phone
- download the [latest source code](https://github.com/SpheroidUniverse/SpheroidScript/tree/master/examples/CoinQuest/src) of the CoinQuest example
- replace the old "Client.spheroid" file in your app by the [new one](https://github.com/SpheroidUniverse/SpheroidScript/blob/master/examples/CoinQuest/src/client/Client.spheroid) from the latest source code
- reupload all files from the "[asses](https://github.com/SpheroidUniverse/SpheroidScript/tree/master/examples/CoinQuest/src/assets)" folder to your app
- note, that in the "Client.spheroid" file we've added "notificationIcon" and "mapIcon" variables in the lines 4 and 6
- note, that in the "assets" folder we've added "[map_icon_gold.png](https://github.com/SpheroidUniverse/SpheroidScript/blob/master/examples/CoinQuest/src/assets/map_icon_gold.png)" and "[notification_icon_gold.png](https://github.com/SpheroidUniverse/SpheroidScript/blob/master/examples/CoinQuest/src/assets/notification_icon_gold.png)" representing the appearance of the coins on the map and in the popup notification

Thanks for the feedback and please let us know if you have any questions!
